package scan

import (
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	// LogoURL is the brand mark placed at the top of exported reports.
	LogoURL = "https://kryptic.dev/logo.png"
	// DefaultReportName is used when --export points at a directory, or when
	// the path is omitted (the directory the command was run from).
	DefaultReportName = "kryptic-scan-report.md"
)

// ExportMeta is the scan context rendered into the Markdown report.
type ExportMeta struct {
	Target    string
	Staged    bool
	Files     int
	Rules     int
	Generated time.Time
	Version   string
}

// ResolveExportPath turns `--export` into a .md file path. An empty path
// (or ".") writes DefaultReportName in the current working directory.
func ResolveExportPath(given string) (string, error) {
	given = strings.TrimSpace(given)
	if given == "" || given == "." {
		cwd, err := os.Getwd()
		if err != nil {
			return "", err
		}
		return filepath.Join(cwd, DefaultReportName), nil
	}

	asDir := strings.HasSuffix(given, "/") || strings.HasSuffix(given, string(os.PathSeparator))
	cleaned := filepath.Clean(given)

	info, err := os.Stat(cleaned)
	if err == nil && info.IsDir() {
		return filepath.Join(cleaned, DefaultReportName), nil
	}
	if asDir {
		if mkdirErr := os.MkdirAll(cleaned, 0o755); mkdirErr != nil {
			return "", mkdirErr
		}
		return filepath.Join(cleaned, DefaultReportName), nil
	}

	if err := os.MkdirAll(filepath.Dir(cleaned), 0o755); err != nil {
		return "", err
	}
	if filepath.Ext(cleaned) == "" {
		cleaned += ".md"
	}
	return cleaned, nil
}

// WriteReport writes a Markdown scan report to path, creating parent dirs.
func WriteReport(path string, findings []Finding, meta ExportMeta) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(RenderMarkdown(findings, meta)), 0o644)
}

// RenderMarkdown builds a branded, self-contained Markdown report. Secrets
// are redacted the same way as the terminal output.
func RenderMarkdown(findings []Finding, meta ExportMeta) string {
	if meta.Generated.IsZero() {
		meta.Generated = time.Now()
	}
	target := meta.Target
	if target == "" {
		target = "."
	}
	if meta.Staged {
		target = "(staged git index)"
	}

	status := "All clear"
	statusDetail := "No secrets matched the embedded gitleaks ruleset."
	if len(findings) == 1 {
		status = "Action required"
		statusDetail = "1 potential secret found. Values below are redacted."
	} else if len(findings) > 1 {
		status = "Action required"
		statusDetail = fmt.Sprintf("%d potential secrets found. Values below are redacted.", len(findings))
	}

	rules := meta.Rules
	if rules == 0 {
		rules = 222
	}
	version := meta.Version
	if version == "" {
		version = "dev"
	}

	var b strings.Builder
	b.WriteString("<!-- Generated by kryptic scan. Secrets are redacted. -->\n\n")
	b.WriteString(`<p align="center">
  <img src="` + LogoURL + `" alt="Kryptic.dev" width="112" height="112" />
</p>

<style>
  :root {
    --kryptic-green: #5ff2a6;
    --kryptic-ink: #04140c;
    --kryptic-bg: #0a0d0c;
    --kryptic-text: #e9f1ec;
    --kryptic-muted: #aab8b0;
    --kryptic-red: #f57b7b;
    --kryptic-surface: #111714;
    --kryptic-border: #232c28;
  }
  .kryptic-report { font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; color: var(--kryptic-text); background: var(--kryptic-bg); border: 1px solid var(--kryptic-border); border-radius: 16px; padding: 8px 20px 16px; }
  .kryptic-hero { text-align: center; padding: 8px 16px 8px; }
  .kryptic-hero h1 { margin: 16px 0 6px; font-size: 1.7rem; letter-spacing: -0.02em; color: var(--kryptic-text); }
  .kryptic-hero p { color: var(--kryptic-muted); margin: 0; line-height: 1.55; }
  .kryptic-banner { border-radius: 10px; padding: 12px 16px; margin: 20px 0; font-weight: 600; }
  .kryptic-banner.ok { background: rgba(95, 242, 166, 0.12); color: var(--kryptic-green); border: 1px solid rgba(95, 242, 166, 0.28); }
  .kryptic-banner.bad { background: rgba(245, 123, 123, 0.12); color: var(--kryptic-red); border: 1px solid rgba(245, 123, 123, 0.28); }
  table { width: 100%; border-collapse: collapse; }
  th { text-align: left; color: var(--kryptic-muted); font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.04em; }
  td, th { padding: 8px 10px; border-bottom: 1px solid var(--kryptic-border); }
  .kryptic-foot { text-align: center; color: var(--kryptic-muted); font-size: 0.85rem; margin-top: 32px; }
  .kryptic-foot a { color: var(--kryptic-green); text-decoration: none; }
</style>

<div class="kryptic-report" align="center">

<div class="kryptic-hero">

<h1>Secret Scan Report</h1>

<p>
`)
	b.WriteString(html.EscapeString(meta.Generated.Format("2 Jan 2006, 15:04 MST")))
	b.WriteString("<br/>\n  Target <code>")
	b.WriteString(html.EscapeString(filepath.ToSlash(target)))
	b.WriteString("</code><br/>\n  kryptic ")
	b.WriteString(html.EscapeString(version))
	b.WriteString(fmt.Sprintf(" · %d rules · local only, nothing left this machine\n</p>\n\n</div>\n\n", rules))

	bannerClass := "ok"
	if len(findings) > 0 {
		bannerClass = "bad"
	}
	b.WriteString(fmt.Sprintf(`<p class="kryptic-banner %s">%s. %s</p>

</div>

---

## Summary

| | |
|---|---|
| **Result** | %s |
| **Files scanned** | %d |
| **Findings** | %d |
| **Ruleset** | gitleaks (%d rules) |
| **Mode** | %s |

`, bannerClass, status, statusDetail, status, meta.Files, len(findings), rules, scanMode(meta.Staged)))

	if len(findings) == 0 {
		b.WriteString("No findings to list.\n\n")
		writeFooter(&b)
		return b.String()
	}

	b.WriteString("## Findings\n\n")
	b.WriteString("| File | Line | Rule | Redacted secret |\n")
	b.WriteString("|------|------|------|------------------|\n")
	for _, finding := range findings {
		fmt.Fprintf(&b, "| %s | %d | %s | `%s` |\n",
			mdCode(finding.File), finding.Line, mdCode(finding.RuleID), mdCell(finding.Redacted()))
	}
	b.WriteString("\n")

	for i, finding := range findings {
		fmt.Fprintf(&b, "### %d. %s:%d · %s\n\n", i+1, finding.File, finding.Line, finding.RuleID)
		if finding.Description != "" {
			b.WriteString(finding.Description)
			b.WriteString("\n\n")
		}
		fmt.Fprintf(&b, "- **File:** %s\n", mdCode(finding.File))
		fmt.Fprintf(&b, "- **Line:** %d\n", finding.Line)
		fmt.Fprintf(&b, "- **Rule:** %s\n", mdCode(finding.RuleID))
		fmt.Fprintf(&b, "- **Secret:** `%s`\n\n", mdCell(finding.Redacted()))
	}

	writeFooter(&b)
	return b.String()
}

func writeFooter(b *strings.Builder) {
	b.WriteString(`---

<p class="kryptic-foot" align="center">
  Generated by <a href="https://kryptic.dev">kryptic.dev</a>. This scan ran fully offline.
</p>
`)
}

func scanMode(staged bool) string {
	if staged {
		return "staged git index"
	}
	return "working tree"
}

func mdCell(value string) string {
	value = strings.ReplaceAll(value, "\r\n", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "|", "\\|")
	return value
}

func mdCode(value string) string {
	value = mdCell(value)
	value = strings.ReplaceAll(value, "`", "'")
	return "`" + value + "`"
}
